import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./component/LayoutWrapper";

export const metadata: Metadata = {
  title: "UI Test",
  description: "UI replication generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
